fix(deps): add nrtk[graphics] extra to fix runtime error
Kitware/nrtk-explorer pull request #131
Opened 2024-10-10 17:48 UTC by PaulHax

nrkt put opencv-python under an extra in 0.12.0 https://github.com/Kitware/nrtk/releases/tag/v0.12.0

2024-10-11 21:37 UTC, jourdain commented
I think we want an offscreen version too, which means we may want to add some optional dependencies `graphic/offscreen`

2024-10-11 21:47 UTC, jourdain requested changes
We need both graphic and offscreen. => Will need an install section in readme since that part will be optional.

2024-10-12 17:15 UTC, PaulHax commented
I look closer.  Methinks we don't need "graphics" option as we don't use `cv2.imshow`.  https://pypi.org/project/opencv-python-headless/

So I changed to just install nrtk[headless] by default.

2024-10-12 20:05 UTC, jourdain approved these changes

2024-10-14 13:39 UTC, merged