All sampled images in image list
Kitware/nrtk-explorer pull request #88
Opened 2024-08-06 20:28 UTC by PaulHax

2024-08-21 16:40 UTC, PaulHax commented
I looked at using `functools.lru_cache` for the `images.get_image` function.  `image.py` code runs some side-effects when a image is dropped from the cache (deletes image frome trame state).  I did not see a "item ejected" callback for `lru_cache`.

2024-08-27 01:02 UTC, vicentebolea commented
@PaulHax it seems that the current BufferCache does not remove the item from the trame cache, in any case I believe that we should detach the cache from the trame state, the evicting instruction is `self.cache.popitem(last=False)`. lru_cache decorator should be able to substitute this.

2024-08-27 01:07 UTC, vicentebolea commented
@PaulHax looks good, I want to better understand this, we went through the changes a couple of weeks ago but I Want to review this in more detail. I wonder if you could edit the description to add a brief note of the feature, the reason for adding the proposed new modules and why we want to change the existing "library" modules.

2024-08-29 16:21 UTC, PaulHax commented
> it seems that the current BufferCache does not remove the item from the trame cache, 

Holy mem leak Batman!  Good catch.  I fix in PR cuz i can't push to this branch anymore =)

If you have an idea on how to use `lru_cache` as user scrolls through long image list i'm all ears.  I still don't know how that would work.

2024-08-29 20:52 UTC, vicentebolea commented
> If you have an idea on how to use lru_cache as user scrolls through long image list i'm all ears. I still don't know how that would work.

How about wrapping the image into a class that implements the __del__ method, the class also has a ref to the state. In this manner the imagewrapper class can deallocate itself from the state just before being destroyed.

2024-09-04 15:50 UTC, PaulHax commented
Refactored `images.py` to use `@lru_cache` for loading and tranforming images with a wrapper the `__del__` trick. 🎉

2024-09-05 02:10 UTC, vicentebolea requested changes
The changes looks good to me, however, I am skeptical of moving data structures to singleton. I wrote a more detailed analysis in the comments among other comments.

I can see how this feature could be implemented without moving the `ImageManager` to a singleton implemented in image.py and I do not see any drawback other than having to instantiate in each application class when is it is not in a `standalone` mode.

I am also skeptical of having another annotations cache singleton too.

Other than that great work in this feature.

2024-09-05 12:50 UTC, PaulHax commented on src/nrtk_explorer/app/images/images.py
> +        self.cache.clear()
How to use `@lru_cache` with the object detection function: 
```
def get_annotations(detector: ObjectDetector, id_to_image: Dict[str, Image.Image]):
```

2024-09-11 15:32 UTC, PaulHax commented on src/nrtk_explorer/app/images/images.py
> +    state.hovered_id = None
In this commit: https://github.com/Kitware/nrtk-explorer/pull/88/commits/d3bd004737024e2e99821e8f4ab1f8a602c7f96b
I've factored out the annotation/obejct-detection code from `images.py`.  `annotations.py` computes/retreaves the annotations and manages the caches.  `stateful_annotations.py` copies the annotations to the trame state.

2024-09-11 15:45 UTC, jourdain approved these changes

2024-09-11 16:04 UTC, merged